networks:
  network2:
    driver: bridge

volumes:
  output-data:
  public-data:

services:
  backend:
    container_name: "gira-backend"
    hostname: "gira-backend"
    build: 
      context: ./back
      dockerfile: ./Dockerfile
    networks:
      - network2
    volumes:
      - output-data:/app/output
      - public-data:/app/public
    restart:
      unless-stopped 
    ports:
      - 192.168.1.10:3332:3332
  frontend:
    container_name: "gira-frontend"
    hostname: "gira-frontend"
    build:
      context: ./front
      dockerfile: ./Dockerfile
    networks:
      - network2
    volumes:
      - output-data:/app/output
    restart:
      unless-stopped
    ports:
      - 192.168.1.10:3002:80
